<%-- Copyright (C) 2011 Cloud.com, Inc.  All rights reserved. --%>
<%@ page language="java" contentType="text/html; charset=UTF-8" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>

<script language="javascript">
if( typeof state_name_to_state_codes === 'undefined' ) {
  var state_name_to_state_codes = {
  'IN.andaman and nicobar islands':'ANI',
  'IN.andhra pradesh':'AP',
  'IN.arunachal pradesh':'ARP',
  'IN.assam':'AS',
  'IN.bihar':'BH',
  'IN.chandigarh':'CHAN',
  'IN.chhattisgarh':'CHAT',
  'IN.dadra and nagar haveli':'DNH',
  'IN.daman and diu':'DD',
  'IN.delhi':'DE',
  'IN.goa':'GO',
  'IN.gujarat':'GU',
  'IN.haryana':'HA',
  'IN.himachal Pradesh':'HI',
  'IN.jammu and kashmir':'JK',
  'IN.jharkhand':'JHA',
  'IN.karnataka':'KAR',
  'IN.kerala':'KER',
  'IN.lakshadweep':'KAK',
  'IN.madhya Pradesh':'MP',
  'IN.maharashtra':'MAH',
  'IN.manipur':'MAN',
  'IN.meghalaya':'MEG',
  'IN.mizoram':'MIZ',
  'IN.magaland':'NAG',
  'IN.orissa':'ORI',
  'IN.pondicherry':'PON',
  'IN.punjab':'PUN',
  'IN.rajasthan':'RAJ',
  'IN.sikkim':'SIK',
  'IN.tamil Nadu':'TN',
  'IN.tripura':'TRI',
  'IN.uttar Pradesh':'UP',
  'IN.uttaranchal':'UTT',
  'IN.west bengal':'WB',
  'US.alaska':'AK',
  'US.alabama':'AL',
  'US.arkansas':'AR',
  'US.arizona':'AZ',
  'US.california':'CA',
  'US.colorado':'CO',
  'US.connecticut':'CT',
  'US.d.c.':'DC',
  'US.delaware':'DE',
  'US.florida':'FL',
  'US.georgia':'GA',
  'US.guam':'GU',
  'US.hawaii':'HI',
  'US.iowa':'IA',
  'US.idaho':'ID',
  'US.illinois':'IL',
  'US.indiana':'IN',
  'US.kansas':'KS',
  'US.kentucky':'KY',
  'US.louisiana':'LA',
  'US.massachusetts':'MA',
  'US.maryland':'MD',
  'US.maine':'ME',
  'US.michigan':'MI',
  'US.minnesota':'MN',
  'US.missouri':'MO',
  'US.mississippi':'MS',
  'US.montana':'MT',
  'US.north carolina':'NC',
  'US.north dakota':'ND',
  'US.nebraska':'NE',
  'US.new hampshire':'NH',
  'US.new jersey':'NJ',
  'US.new nexico':'NM',
  'US.nevada':'NV',
  'US.new york':'NY',
  'US.ohio':'OH',
  'US.oklahoma':'OK',
  'US.oregon':'OR',
  'US.pennsylvania':'PA',
  'US.puerto rico':'PR',
  'US.rhode island':'RI',
  'US.south carolina':'SC',
  'US.south dakota':'SD',
  'US.tennessee':'TN',
  'US.texas':'TX',
  'US.utah':'UT',
  'US.virginia':'VA',
  'US.virgin islands':'VI',
  'US.vermont':'VT',
  'US.washington':'WA',
  'US.wisconsin':'WI',
  'US.west virginia':'WV',
  'US.wyoming':'WY',
  'US.military americas':'AA',
  'US.military europe/me/canada':'AE',
  'US.military pacific':'AP',    
  'CA.alberta':'AB',
  'CA.manitoba':'MB',
  'CA.british columbia':'BC',
  'CA.new brunswick':'NB',
  'CA.newfoundland and labrador':'NL',
  'CA.nova scotia':'NS',
  'CA.northwest territories':'NT',
  'CA.nunavut':'NU',
  'CA.ontario':'ON',
  'CA.prince edward island':'PE',
  'CA.quebec':'QC',
  'CA.saskatchewan':'SK',
  'CA.yukon territory':'YT',
  'AU.australian capital territory':'ACT',
  'AU.new south wales':'NSW',
  'AU.northern territory':'NT',      
  'AU.queensland':'QLD',
  'AU.south australia':'SA',
  'AU.tasmania':'TAS',
  'AU.victoria':'VIC',
  'AU.western australia':'WA' 
  };
};
</script>